# Site settings
title: bitminion
url: "http://bitminion.com"
twitter_username: bitminion
github_username: bitminion

# Build settings
markdown: kramdown
permalink: pretty

# analytics settings
analytics: google
analytics_id: UA-54374405-1